/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario_funcionario;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FLAVIO RICARDO
 */
public class Formulario extends javax.swing.JFrame {
    ArrayList<Funcionarios> ListaF;
     ;
    public void LaodtTableFuncionario(){
        DefaultTableModel modelo = new DefaultTableModel(new Object  []  {"codigo","apelido","nome completo","data nascimento","numeroBI","genero","naturalidade","email",
         "salario","Estado Civil", "contactos", "endereco","observacao"} , 0 );
                  

        
        for (int i = 0 ; i < ListaF.size(); i++){
            Object linha []= new Object []{ListaF.get(i).getCódigo(),ListaF.get(i).getApelido(),
                                         ListaF.get(i).getNomeCompleto(),ListaF.get(i).getDataNascimento(),
                                         ListaF.get(i).getGenero(),ListaF.get(i).getNaturalidade(), 
                                         ListaF.get(i).getNumeroBI(), ListaF.get(i).getContactos(), ListaF.get(i).getEmail(),
                                         ListaF.get(i).getEstadoCivil(),ListaF.get(i).getEndereco(), ListaF.get(i).getSalario(),
                                         ListaF.get(i).getObservacao()};
            
            modelo.addRow(linha);
             tabela1.getColumnModel().getColumn(0).setPreferredWidth(50);
        
        }
        
        tabela1.setModel(modelo);
    }

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        setLocationRelativeTo(null);
        ListaF = new   ArrayList(); 
        btn_salvar.setEnabled(false);
        btn_cancelar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_apelido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_data = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_bi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txt_naturalidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_contatos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_estado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_endereco = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_salario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_observacao = new javax.swing.JTextField();
        btn_salvar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_novo = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Apelido", "Nome ", "Data Nascimento", "numero BI", "Sexo", "Naturalidade", "E-mail", "Contactos", "Estado Civil", "Endereco", "Salario", "Observacao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela1);
        if (tabela1.getColumnModel().getColumnCount() > 0) {
            tabela1.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados"));

        jLabel1.setText("Codigo");

        txt_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codigoKeyTyped(evt);
            }
        });

        jLabel2.setText("Apelido");

        txt_apelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apelidoKeyTyped(evt);
            }
        });

        jLabel3.setText("Nome Completo");

        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });
        txt_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomeKeyTyped(evt);
            }
        });

        jLabel4.setText("Data Nascimento");

        txt_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dataActionPerformed(evt);
            }
        });
        txt_data.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dataKeyTyped(evt);
            }
        });

        jLabel5.setText("Numero BI");

        txt_bi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_biKeyTyped(evt);
            }
        });

        jLabel6.setText("Genero");

        jRadioButton1.setText("M");

        jRadioButton2.setText("F");

        jLabel7.setText("Naturalidade");

        txt_naturalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_naturalidadeKeyTyped(evt);
            }
        });

        jLabel8.setText("Contactos");

        txt_contatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_contatosKeyTyped(evt);
            }
        });

        jLabel9.setText("Estado Civil");

        txt_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_estadoActionPerformed(evt);
            }
        });
        txt_estado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_estadoKeyTyped(evt);
            }
        });

        jLabel10.setText("Enderenco");

        txt_endereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_enderecoKeyTyped(evt);
            }
        });

        jLabel11.setText("Salario");

        txt_salario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_salarioKeyTyped(evt);
            }
        });

        jLabel12.setText("Observacao");

        txt_observacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_observacaoActionPerformed(evt);
            }
        });
        txt_observacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_observacaoKeyTyped(evt);
            }
        });

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(jRadioButton2))
                    .addComponent(txt_apelido)
                    .addComponent(txt_bi)
                    .addComponent(txt_naturalidade)
                    .addComponent(txt_codigo)
                    .addComponent(txt_nome)
                    .addComponent(txt_data))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_contatos)
                    .addComponent(txt_estado)
                    .addComponent(txt_endereco)
                    .addComponent(txt_salario)
                    .addComponent(txt_observacao, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addComponent(btn_salvar)
                .addGap(84, 84, 84)
                .addComponent(btn_cancelar)
                .addGap(0, 186, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_contatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_estado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_apelido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_endereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(txt_salario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_bi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txt_naturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txt_observacao, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_salvar)
                        .addComponent(btn_cancelar)))
                .addContainerGap())
        );

        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");

        btn_editar.setText("Editar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_novo)
                .addGap(86, 86, 86)
                .addComponent(btn_editar)
                .addGap(94, 94, 94)
                .addComponent(btn_eliminar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_novo)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_editar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Funcionarios", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void txt_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dataActionPerformed

    private void txt_apelidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apelidoKeyTyped
                                          
   String caracter ="0987654321@!#$%^&*()-_+=][|;'º.,''´´«»></?`~\\{}: "; 
   if(caracter.contains(evt.getKeyChar()+"")){
       evt.consume();
       JOptionPane.showMessageDialog(rootPane," nao podes usar numero nem caracteres especiais");
   }                                 

    }//GEN-LAST:event_txt_apelidoKeyTyped

    private void txt_nomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomeKeyTyped
                                           
   String caracter ="0987654321@!#$%^&*()-_+=][|;'º.,''´´«»></?`~\\{}: "; 
   if(caracter.contains(evt.getKeyChar()+"")){
       evt.consume();
       JOptionPane.showMessageDialog(rootPane," nao podes usar numero nem caracteres especiais");
   }
                                  

    }//GEN-LAST:event_txt_nomeKeyTyped

    private void txt_naturalidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_naturalidadeKeyTyped
                                         
   String caracter ="0987654321@!#$%^&*()-_+=][|;'º.,''´´«»></?`~\\{}: "; 
   if(caracter.contains(evt.getKeyChar()+"")){
       evt.consume();
       JOptionPane.showMessageDialog(rootPane," nao podes usar numero nem caracteres especiais");
   }
                                    

    }//GEN-LAST:event_txt_naturalidadeKeyTyped

    private void txt_estadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_estadoKeyTyped
                                          
   String caracter ="0987654321@!#$%^&*()-_+=][|;'º.,''´´«»></?`~\\{}: "; 
   if(caracter.contains(evt.getKeyChar()+"")){
       evt.consume();
            JOptionPane.showMessageDialog(rootPane," nao podes usar numero nem caracteres especiais");
   }
                                      

    }//GEN-LAST:event_txt_estadoKeyTyped

    private void txt_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyTyped
                                       
   String caracter ="ABCDEFGHIJKLMNOPQRSTUVXWYZabcdefghijklmnopqrstuvwyz@!§#$%^&*()-_+=][|;'º.,''´´«»></?`~\\{}: "; 
   if(caracter.contains(evt.getKeyChar()+"")){
       evt.consume();
       JOptionPane.showMessageDialog(rootPane," usar somente numeros");
       
   }
   
                                      

    }//GEN-LAST:event_txt_codigoKeyTyped

    private void txt_dataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dataKeyTyped
       
          String caracter ="ABCDEFGHIJKLMNOPQRSTUVXWYZabcdefghijklmnopqrstuvwyz@!#$%^&*()_+=][;'º.,''´´«»><?`~\\{}: "; 
   if(caracter.contains(evt.getKeyChar()+"")){
       evt.consume();
       JOptionPane.showMessageDialog(rootPane," usar somente numeros , -|/");
   }
 
        //JOptionPane.showMessageDialog(rootPane," nao podes usar numero nem caracteres especiais");
    }//GEN-LAST:event_txt_dataKeyTyped

    private void txt_salarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_salarioKeyTyped
        String caracter ="ABCDEFGHIJKLMNOPQRSTUVXWYZabcdefghijklmnopqrstuvwyz@!#$%^&*()-_+=][|;'º''´´«»></?`~\\{}: "; 
   if(caracter.contains(evt.getKeyChar()+"")){
       evt.consume();
       JOptionPane.showMessageDialog(rootPane," usar somente NUMEROS ");
   }
    }//GEN-LAST:event_txt_salarioKeyTyped

    private void txt_enderecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_enderecoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enderecoKeyTyped

    private void txt_contatosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contatosKeyTyped
    String caracter ="ABCDEFGHIJKLMNOPQRSTUVXWYZabcdefghijklmnopqrstuvwyz@!#$%^&*()_+|/-=][;'º.,  ''´´«»><?`~\\{}: "; 
    if(caracter.contains(evt.getKeyChar()+"")){
       evt.consume();
       JOptionPane.showMessageDialog(rootPane," usar somente NUMEROS" );
    }//GEN-LAST:event_txt_contatosKeyTyped
    }
    private void txt_biKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_biKeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_txt_biKeyTyped

    private void txt_observacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_observacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_observacaoActionPerformed

    private void txt_observacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_observacaoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_observacaoKeyTyped

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        txt_codigo.setText("");
        txt_apelido.setText("");
        txt_nome.setName("");
        txt_data.setText("");
        txt_bi.setText("");
        txt_naturalidade.setText("");
        txt_contatos.setText("");
        txt_estado.setText("");
        txt_endereco.setText("");
        txt_salario.setText("");
        txt_observacao.setText("");
        
        btn_salvar.setEnabled(true);
        btn_cancelar.setEnabled(true);
    }//GEN-LAST:event_btn_novoActionPerformed

    private void txt_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estadoActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        btn_salvar.setEnabled(false);
        btn_cancelar.setEnabled(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        
         //cod = Integer.parseInt(txt_codigo.getText());
        int cont = Integer.parseInt(txt_contatos.getText());
        double sal= Double.parseDouble(txt_salario.getText());
     // Funcionarios F = new Funcionarios( txt_codigo.getText(),txt_apelido.getText(),txt_nome.getText(),
       //         txt_data.getText(),txt_bi.getText(),txt_naturalidade.getText(),
         //       cont,txt_estado.getText(),txt_endereco.getText(),txt_observacao.getText(),sal);
                
        Funcionarios F = new Funcionarios ();
        ListaF.add(F);

        
        LaodtTableFuncionario();
        
    }//GEN-LAST:event_btn_salvarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater (new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        
    });
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabela1;
    private javax.swing.JTextField txt_apelido;
    private javax.swing.JTextField txt_bi;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_contatos;
    private javax.swing.JTextField txt_data;
    private javax.swing.JTextField txt_endereco;
    private javax.swing.JTextField txt_estado;
    private javax.swing.JTextField txt_naturalidade;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_observacao;
    private javax.swing.JTextField txt_salario;
    // End of variables declaration//GEN-END:variables
}
